#!/usr/bin/env perl

use strict;
use warnings;
use utf8;
use v5.14;

use lib qw (lib);
use GrowBot;

# Set the script name.
$0 = "growbot";

my $configFile = "config.json";

my $growbot = GrowBot->new ($configFile);

# Capture SIGHUP to allow for the configuration file to be reloaded.
$SIG{HUP} = sub {
  $growbot = GrowBot->new ($configFile);
};
# Capture SIGINT, and SIGTERM to allow for a graceful exit.
$SIG{INT} = $SIG{TERM} = sub { $growbot->{running} = 0 };

printf "%s %s\n", $growbot->name, $growbot->version;


$growbot->start;


$growbot->close;

printf "Done.\n";
