#!/usr/bin/env perl

=head1 NAME

  GrowBot

=head1 SYNOPSIS


=head1 DESCRIPTION


=head1 DEPENDENCIES

GrowBot requires Perl version 5.14 or later, in addition to Mojolicious.

=head1 FEEDBACK

=head2 Reporting Bugs

Report bugs to the GitHub issue tracker at:
  https://github.com/sandain/growbot/issues

=head1 AUTHOR - Jason M. Wood

Email sandain@hotmail.com

=head1 COPYRIGHT AND LICENSE

  Copyright (c) 2020-2022  Jason M. Wood <sandain@hotmail.com>

  All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are met:

  1. Redistributions of source code must retain the above copyright notice,
     this list of conditions and the following disclaimer.
  2. Redistributions in binary form must reproduce the above copyright
     notice, this list of conditions and the following disclaimer in the
     documentation and/or other materials provided with the distribution.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
  POSSIBILITY OF SUCH DAMAGE.

=cut

use strict;
use warnings;
use utf8;
use open qw (:std :utf8);
use v5.14;

use lib qw (lib);
use GrowBot;

use Encode qw (encode_utf8);
use Mojolicious::Lite;
use Mojo::JSON qw (to_json);

use lib qw (lib);

my $configFile = "config.json";
my $growbot = GrowBot->new ($configFile);


=head2 Helper Functions

=head3 config

  Return configuration information.

=cut

helper 'config' => sub {
  my $self = shift;
  return $growbot->{config};
};


helper 'data' => sub {
  my $self = shift;
  my ($device, $measurement, $type, $indent) = @_;
  my $filepath = sprintf "%s/%s/%s.%s",
    $growbot->dataFolder, $device, $measurement, $type;
  return unless (-s $filepath);
  open my $fh, '<', $filepath or die "Can't load data: $!";
  my $data = join " " x $indent, <$fh>;
  close $fh;
  return $data;
};

helper 'devices' => sub {
  my $self = shift;
  return sort $growbot->devices;
};

=head3 device

  Return device data.

=cut

helper 'device' => sub {
  my $self = shift;
  my ($name) = @_;
  my $folder = sprintf "%s/%s", $growbot->dataFolder, $name;
  my $data = "{";
  $data .= sprintf "\"name\": \"%s\",", $name;
  $data .= sprintf "\"type\": \"%s\",", $self->config->{Devices}{$name}{Type};
  $data .= sprintf "\"measurements\": {";
  my @actions = @{$self->config->{Devices}{$name}{Actions}};
  for (my $i = 0; $i < @actions; $i ++) {
    next unless (defined $self->config->{Actions}{$actions[$i]}{Results});
    my @results = @{$self->config->{Actions}{$actions[$i]}{Results}};
    for (my $j = 0; $j < @results; $j ++) {
      next unless ($self->config->{Results}{$results[$j]}{Type});
      my $type = $self->config->{Results}{$results[$j]}{Type};
      open my $fh, '<', "$folder/$type.txt" or die "Can't open file: $!";
      my $measure = join "", <$fh>;
      close $fh;
      $measure =~ s/[\r\n]+//;
      my @measure = split /\t/, $measure;
      $data .= "," unless ($i + $j == 0);
      $data .= sprintf "\"%s\": {", $type;
      $data .= sprintf "\"time\": \"%s\",", $measure[0];
      $data .= sprintf "\"measure\": \"%s\",", $measure[1];
      $data .= sprintf "\"unit\": \"%s\"", (defined $measure[2] ? $measure[2] : "");
      $data .= "}"
    }
  }
  $data .= "}}";
  return encode_utf8 $data;
};


=head2 HTTP Request Methods

=head3 get /

  Renders the dashboard.

=cut

get '/' => sub {
  my $self = shift;
  $self->render (template => 'dashboard');
};

=head3 get /device/<device name>

  Renders the dashboard.

=cut

get '/device/:name' => sub {
  my $self = shift;
  my $name = $self->param ('name');
  $self->render (template => 'device');
};

get '/device/:name/:type' => sub {
  my $self = shift;
  my $name = $self->param ('name');
  my $type = $self->param ('type');
  $self->render (template => 'device_type');
};

app->start;
